{
 "title": "Pod Disk Latency Monitoring (ms)",
 "tags": [
  "kubernetes",
  "pods",
  "disk",
  "latency",
  "performance",
  "io"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Disk Latency (Milliseconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Pod Disk Read Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  sum by (namespace, pod) (rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m]))\n  /\n  clamp_min(sum by (namespace, pod) (rate(container_fs_reads_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m])), 0.001)\n) / 1000",
     "legendFormat": "{{namespace}}/{{pod}} - Read Latency",
     "uid": "prometheus"
    }
   ]
  },
  {
   "title": "Pod Disk Write Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  sum by (namespace, pod) (rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m]))\n  /\n  clamp_min(sum by (namespace, pod) (rate(container_fs_writes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m])), 0.001)\n) / 1000",
     "legendFormat": "{{namespace}}/{{pod}} - Write Latency",
     "uid": "prometheus"
    }
   ]
  },
  {
   "title": "Node Disk Latency (Affecting Pods)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_io_time_weighted_seconds_total{instance=~\".*\"}[5m]) / \n  clamp_min(\n    rate(node_disk_reads_completed_total{instance=~\".*\"}[5m]) + \n    rate(node_disk_writes_completed_total{instance=~\".*\"}[5m]), \n    0.001\n  )\n) * 1000",
     "legendFormat": "{{instance}} - {{device}} - Disk Latency",
     "uid": "prometheus"
    }
   ]
  },
  { "title": "Pod Latency Rankings (ms)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top 10 Pods by Read Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  (\n    sum by (namespace, pod) (rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m]))\n    /\n    clamp_min(sum by (namespace, pod) (rate(container_fs_reads_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m])), 0.001)\n  ) / 1000\n)",
     "legendFormat": "{{namespace}}/{{pod}}",
     "uid": "prometheus"
    }
   ]
  },
  {
   "title": "Top 10 Pods by Write Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  (\n    sum by (namespace, pod) (rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m]))\n    /\n    clamp_min(sum by (namespace, pod) (rate(container_fs_writes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m])), 0.001)\n  ) / 1000\n)",
     "legendFormat": "{{namespace}}/{{pod}}",
     "uid": "prometheus"
    }
   ]
  },
  { "title": "Pod I/O Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pod I/O Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(container_fs_reads_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m]))",
     "legendFormat": "{{namespace}}/{{pod}} - Read Ops/s",
     "uid": "prometheus"
    },
    {
     "expr": "sum by (namespace, pod) (rate(container_fs_writes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m]))",
     "legendFormat": "{{namespace}}/{{pod}} - Write Ops/s",
     "uid": "prometheus"
    }
   ]
  },
  {
   "title": "Pod I/O Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m]))",
     "legendFormat": "{{namespace}}/{{pod}} - Read Throughput",
     "uid": "prometheus"
    },
    {
     "expr": "sum by (namespace, pod) (rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\"}[5m]))",
     "legendFormat": "{{namespace}}/{{pod}} - Write Throughput",
     "uid": "prometheus"
    }
   ]
  },
  { "title": "Pod to Node Mapping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pod Node Assignment",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "uid": "prometheus"
    }
   ]
  }
 ]
}